#!/usr/bin/env python3
"""Analytical cabinet impulse-response synthesiser.

WHY THIS EXISTS
---------------
Bundling a cabinet impulse response means redistributing a recording inside
every copy of an AGPLv3 binary. Third-party IR packs make that a licensing
question that is frequently unanswerable: a capture carries rights from the
cabinet, from the microphone, and from the person who pressed record, and
mirrors routinely misstate all three.

This script sidesteps the question entirely. Every IR it emits is *computed*
from a documented analytical model - a cascade of standard analog-prototype
filter sections plus sparse reflection taps - and therefore contains no
third-party recording at all. The generator is the provenance: run it, get
byte-identical output, compare the SHA-256. That is a stronger licence
argument than any pack's README.

WHAT THESE ARE, AND WHAT THEY ARE NOT
-------------------------------------
These are MODELS. They are not captures of any particular cabinet, speaker or
microphone, they are not measurements, and they must never be labelled as if
they were. Every display name carries a "Modelled" prefix for exactly that
reason. The models are voiced from the well-documented behaviour of moving-coil
loudspeakers in boxes - driver/box high-pass alignment, cone-breakup modes,
voice-coil-inductance roll-off, baffle and floor reflections, microphone
proximity and off-axis behaviour - not from anyone's recording.

MODEL STRUCTURE
---------------
Each model is one or more parallel *paths* (a woofer path, optionally a horn
path), each path being a gain, an integer sample delay, and an ordered chain of
biquad sections. The summed direct field is then run through a sparse FIR of
reflection taps whose delays are derived from a physical path-length difference
in centimetres at 343 m/s, and optionally summed with a decaying diffuse tail
generated by an explicitly-seeded LCG.

Filter sections use the standard bilinear-transform designs (RBJ audio EQ
cookbook), evaluated in float64. There is no randomness anywhere except the
diffuse tail, whose generator and seed are part of the model definition, so the
output is bit-identical on any machine with an IEEE-754 double.

DEPENDENCIES
------------
The Python standard library, and nothing else. No numpy, no scipy, no network
access. This is deliberate: a generator that needs a pinned scientific stack to
reproduce its output is a weaker reproducibility claim than one that does not.

USAGE
-----
    python3 cabsynth.py --out-dir ../../resources/irs --models bass
    python3 cabsynth.py --list
    python3 cabsynth.py --manifest manifest.json --out-dir out
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import struct
import sys

# Speed of sound in air at 20 degrees C, in metres per second. Used to convert
# a reflection's excess path length (in centimetres) into a delay in samples.
SPEED_OF_SOUND_M_PER_S = 343.0


# ---------------------------------------------------------------------------
# Biquad section design (bilinear transform, RBJ audio EQ cookbook forms).
# Coefficients are returned normalised to a0 = 1 as (b0, b1, b2, a1, a2).
# ---------------------------------------------------------------------------

def _rbj_common(freq_hz, sample_rate, q):
    w0 = 2.0 * math.pi * freq_hz / sample_rate
    cos_w0 = math.cos(w0)
    sin_w0 = math.sin(w0)
    alpha = sin_w0 / (2.0 * q)
    return w0, cos_w0, sin_w0, alpha


def biquad_lowpass(freq_hz, sample_rate, q):
    _, cos_w0, _, alpha = _rbj_common(freq_hz, sample_rate, q)
    b0 = (1.0 - cos_w0) / 2.0
    b1 = 1.0 - cos_w0
    b2 = (1.0 - cos_w0) / 2.0
    a0 = 1.0 + alpha
    a1 = -2.0 * cos_w0
    a2 = 1.0 - alpha
    return (b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def biquad_highpass(freq_hz, sample_rate, q):
    _, cos_w0, _, alpha = _rbj_common(freq_hz, sample_rate, q)
    b0 = (1.0 + cos_w0) / 2.0
    b1 = -(1.0 + cos_w0)
    b2 = (1.0 + cos_w0) / 2.0
    a0 = 1.0 + alpha
    a1 = -2.0 * cos_w0
    a2 = 1.0 - alpha
    return (b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def biquad_highpass1(freq_hz, sample_rate, q=None):
    """First-order high-pass, expressed as a biquad with b2 = a2 = 0.

    Used for the 6 dB/octave dipole roll-off of an open-back cabinet, which is
    a first-order slope and would be misrepresented by a second-order section.
    """
    k = math.tan(math.pi * freq_hz / sample_rate)
    norm = 1.0 / (1.0 + k)
    return (norm, -norm, 0.0, (k - 1.0) * norm, 0.0)


def biquad_peaking(freq_hz, sample_rate, q, gain_db):
    amp = 10.0 ** (gain_db / 40.0)
    _, cos_w0, _, alpha = _rbj_common(freq_hz, sample_rate, q)
    b0 = 1.0 + alpha * amp
    b1 = -2.0 * cos_w0
    b2 = 1.0 - alpha * amp
    a0 = 1.0 + alpha / amp
    a1 = -2.0 * cos_w0
    a2 = 1.0 - alpha / amp
    return (b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def biquad_lowshelf(freq_hz, sample_rate, q, gain_db):
    amp = 10.0 ** (gain_db / 40.0)
    w0, cos_w0, sin_w0, _ = _rbj_common(freq_hz, sample_rate, q)
    alpha = sin_w0 / 2.0 * math.sqrt((amp + 1.0 / amp) * (1.0 / q - 1.0) + 2.0)
    two_sqrt_a_alpha = 2.0 * math.sqrt(amp) * alpha
    b0 = amp * ((amp + 1.0) - (amp - 1.0) * cos_w0 + two_sqrt_a_alpha)
    b1 = 2.0 * amp * ((amp - 1.0) - (amp + 1.0) * cos_w0)
    b2 = amp * ((amp + 1.0) - (amp - 1.0) * cos_w0 - two_sqrt_a_alpha)
    a0 = (amp + 1.0) + (amp - 1.0) * cos_w0 + two_sqrt_a_alpha
    a1 = -2.0 * ((amp - 1.0) + (amp + 1.0) * cos_w0)
    a2 = (amp + 1.0) + (amp - 1.0) * cos_w0 - two_sqrt_a_alpha
    return (b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


def biquad_highshelf(freq_hz, sample_rate, q, gain_db):
    amp = 10.0 ** (gain_db / 40.0)
    w0, cos_w0, sin_w0, _ = _rbj_common(freq_hz, sample_rate, q)
    alpha = sin_w0 / 2.0 * math.sqrt((amp + 1.0 / amp) * (1.0 / q - 1.0) + 2.0)
    two_sqrt_a_alpha = 2.0 * math.sqrt(amp) * alpha
    b0 = amp * ((amp + 1.0) + (amp - 1.0) * cos_w0 + two_sqrt_a_alpha)
    b1 = -2.0 * amp * ((amp - 1.0) + (amp + 1.0) * cos_w0)
    b2 = amp * ((amp + 1.0) + (amp - 1.0) * cos_w0 - two_sqrt_a_alpha)
    a0 = (amp + 1.0) - (amp - 1.0) * cos_w0 + two_sqrt_a_alpha
    a1 = 2.0 * ((amp - 1.0) - (amp + 1.0) * cos_w0)
    a2 = (amp + 1.0) - (amp - 1.0) * cos_w0 - two_sqrt_a_alpha
    return (b0 / a0, b1 / a0, b2 / a0, a1 / a0, a2 / a0)


_SECTION_DESIGNERS = {
    "lowpass": lambda s, sr: biquad_lowpass(s["freq"], sr, s["q"]),
    "highpass": lambda s, sr: biquad_highpass(s["freq"], sr, s["q"]),
    "highpass1": lambda s, sr: biquad_highpass1(s["freq"], sr),
    "peak": lambda s, sr: biquad_peaking(s["freq"], sr, s["q"], s["gain_db"]),
    "lowshelf": lambda s, sr: biquad_lowshelf(s["freq"], sr, s["q"], s["gain_db"]),
    "highshelf": lambda s, sr: biquad_highshelf(s["freq"], sr, s["q"], s["gain_db"]),
}


def apply_biquad(signal, coeffs):
    """Direct Form I, float64, zero initial state."""
    b0, b1, b2, a1, a2 = coeffs
    x1 = x2 = y1 = y2 = 0.0
    out = [0.0] * len(signal)
    for n, x0 in enumerate(signal):
        y0 = b0 * x0 + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2
        out[n] = y0
        x2, x1 = x1, x0
        y2, y1 = y1, y0
    return out


def apply_chain(signal, stages, sample_rate):
    out = signal
    for stage in stages:
        designer = _SECTION_DESIGNERS[stage["type"]]
        out = apply_biquad(out, designer(stage, sample_rate))
    return out


# ---------------------------------------------------------------------------
# Deterministic noise for the diffuse tail of a room model.
#
# An explicit 64-bit LCG (the constants are Knuth's MMIX ones) rather than
# random.Random, so the sample stream is defined by this file alone and cannot
# drift with a Python release.
# ---------------------------------------------------------------------------

class Lcg:
    MULTIPLIER = 6364136223846793005
    INCREMENT = 1442695040888963407
    MODULUS = 1 << 64

    def __init__(self, seed):
        self.state = seed % self.MODULUS

    def next_bipolar(self):
        self.state = (self.state * self.MULTIPLIER + self.INCREMENT) % self.MODULUS
        # Take the top 32 bits: the low bits of an LCG have short periods.
        top = self.state >> 32
        return (top / 2147483648.0) - 1.0


# ---------------------------------------------------------------------------
# Radix-2 FFT (iterative, in-place Cooley-Tukey) - used only for the
# normalisation measurement, never in the IR itself.
# ---------------------------------------------------------------------------

def fft(values):
    n = len(values)
    if n & (n - 1) != 0:
        raise ValueError("FFT length must be a power of two")

    data = list(values)
    j = 0
    for i in range(1, n):
        bit = n >> 1
        while j & bit:
            j ^= bit
            bit >>= 1
        j |= bit
        if i < j:
            data[i], data[j] = data[j], data[i]

    length = 2
    while length <= n:
        angle = -2.0 * math.pi / length
        step = complex(math.cos(angle), math.sin(angle))
        for start in range(0, n, length):
            w = complex(1.0, 0.0)
            half = length >> 1
            for k in range(start, start + half):
                u = data[k]
                v = data[k + half] * w
                data[k] = u + v
                data[k + half] = u - v
                w *= step
        length <<= 1
    return data


def magnitude_response(impulse, fft_size):
    padded = [complex(x, 0.0) for x in impulse] + [0j] * (fft_size - len(impulse))
    spectrum = fft(padded)
    return [abs(spectrum[k]) for k in range(fft_size // 2 + 1)]


# ---------------------------------------------------------------------------
# Model rendering
# ---------------------------------------------------------------------------

def delay_samples_for_path_cm(path_cm, sample_rate):
    seconds = (path_cm / 100.0) / SPEED_OF_SOUND_M_PER_S
    return int(round(seconds * sample_rate))


def render_model(model):
    sample_rate = model["sample_rate"]
    length = model["length"]

    # Render each parallel path from its own unit impulse, then sum. Rendering
    # at 4x the final length and truncating afterwards keeps the tail of a
    # resonant section from being cut before it has decayed into the noise.
    work_length = length * 4
    summed = [0.0] * work_length

    for path in model["paths"]:
        impulse = [0.0] * work_length
        impulse[0] = 1.0
        rendered = apply_chain(impulse, path["stages"], sample_rate)
        gain = path.get("gain", 1.0)
        delay = path.get("delay_samples", 0)
        for n in range(work_length - delay):
            summed[n + delay] += gain * rendered[n]

    # Sparse reflection FIR. Each tap is a copy of the whole direct field,
    # delayed by its excess path length and scaled; a negative gain models a
    # polarity-inverting boundary interaction.
    reflected = list(summed)
    for reflection in model.get("reflections", []):
        delay = delay_samples_for_path_cm(reflection["path_cm"], sample_rate)
        gain = reflection["gain"]
        # A reflection has travelled further through air and off a surface, so
        # it arrives duller than the direct sound.
        damped = apply_chain(summed, reflection.get("stages", []), sample_rate)
        for n in range(work_length - delay):
            reflected[n + delay] += gain * damped[n]

    tail_spec = model.get("tail")
    if tail_spec is not None:
        reflected = _add_diffuse_tail(reflected, tail_spec, model, work_length)

    truncated = reflected[:length]

    # Raised-cosine fade so truncation cannot leave a step discontinuity (which
    # would read as broadband splatter in the frequency response).
    fade = model.get("fade_samples", max(16, length // 4))
    fade = min(fade, length)
    for i in range(fade):
        position = i / float(fade)
        truncated[length - fade + i] *= 0.5 * (1.0 + math.cos(math.pi * position))

    return truncated


def _add_diffuse_tail(direct, tail_spec, model, work_length):
    sample_rate = model["sample_rate"]
    rng = Lcg(tail_spec["seed"])
    decay_tau = tail_spec["decay_seconds"] * sample_rate
    predelay = delay_samples_for_path_cm(tail_spec["predelay_cm"], sample_rate)

    noise = [0.0] * work_length
    for n in range(predelay, work_length):
        noise[n] = rng.next_bipolar() * math.exp(-(n - predelay) / decay_tau)

    shaped = apply_chain(noise, tail_spec.get("stages", []), sample_rate)

    # Level the tail against the direct field by energy, so the documented
    # "tail is N dB below direct" number means what it says.
    direct_energy = math.sqrt(sum(v * v for v in direct)) or 1.0
    tail_energy = math.sqrt(sum(v * v for v in shaped)) or 1.0
    scale = (direct_energy / tail_energy) * (10.0 ** (tail_spec["level_db"] / 20.0))

    return [direct[n] + scale * shaped[n] for n in range(work_length)]


def normalise_unity_peak_response(impulse, fft_size=65536):
    """Scale so that max |H(f)| == 1.0 (0 dBFS).

    Chosen over peak-sample or energy normalisation because it is the criterion
    that actually bounds the convolution: with the maximum of the magnitude
    response at unity, no sine at any frequency can leave the convolver louder
    than it entered, so a full-scale input cannot be driven into clipping by
    the IR alone. It is also trivially verifiable after the fact, which matters
    more here than matching anyone's loudness convention - both host plugins
    apply their own IR gain staging downstream.
    """
    response = magnitude_response(impulse, fft_size)
    peak = max(response)
    if peak <= 0.0:
        raise ValueError("degenerate impulse response: zero magnitude everywhere")
    scale = 1.0 / peak
    return [v * scale for v in impulse], scale, peak


# ---------------------------------------------------------------------------
# 24-bit PCM WAV writing (little-endian, mono or multi-channel interleaved).
# ---------------------------------------------------------------------------

def write_wav24(path, samples, sample_rate):
    num_channels = 1
    bits_per_sample = 24
    bytes_per_sample = bits_per_sample // 8
    block_align = num_channels * bytes_per_sample
    byte_rate = sample_rate * block_align

    frames = bytearray()
    clipped = 0
    peak_code = 0
    limit = (1 << 23) - 1
    for value in samples:
        # Round-half-away-from-zero to a symmetric 24-bit range. The symmetric
        # range (rather than -2^23) means a full-scale negative sample cannot
        # wrap, and the clip counter below must stay at zero for every shipped
        # asset.
        code = int(math.floor(abs(value) * limit + 0.5))
        if code > limit:
            code = limit
            clipped += 1
        peak_code = max(peak_code, code)
        if value < 0.0:
            code = -code
        frames += struct.pack("<i", code)[:3]

    data_size = len(frames)
    riff_size = 4 + (8 + 16) + (8 + data_size) + (data_size % 2)

    with open(path, "wb") as handle:
        handle.write(b"RIFF")
        handle.write(struct.pack("<I", riff_size))
        handle.write(b"WAVE")
        handle.write(b"fmt ")
        handle.write(struct.pack("<IHHIIHH", 16, 1, num_channels, sample_rate,
                                 byte_rate, block_align, bits_per_sample))
        handle.write(b"data")
        handle.write(struct.pack("<I", data_size))
        handle.write(bytes(frames))
        if data_size % 2:
            handle.write(b"\x00")

    return clipped, peak_code / float(limit)


# ---------------------------------------------------------------------------
# The models.
#
# Every number below is a voicing decision, and every one of them is visible
# here rather than baked into an opaque asset. The comments state what each
# group of sections is modelling so the table can be argued with, adjusted and
# re-run.
# ---------------------------------------------------------------------------

def _dynamic_close_mic(proximity_db, proximity_hz=140.0, presence_db=2.5,
                       presence_hz=5200.0):
    """A generic cardioid dynamic microphone, close to the grille.

    Two effects, both first-principles rather than modelled on any particular
    microphone: the pressure-gradient proximity rise at close range (a
    low-shelf), and the mild presence lift a cardioid dynamic's diaphragm
    resonance contributes.
    """
    return [
        {"type": "lowshelf", "freq": proximity_hz, "q": 0.7, "gain_db": proximity_db},
        {"type": "peak", "freq": presence_hz, "q": 1.2, "gain_db": presence_db},
    ]


def _off_axis(corner_hz, shelf_db, extra_lp_hz):
    """Off-axis / cone-edge microphone placement.

    A cone radiates its high frequencies far more directionally than its lows,
    so moving the microphone off the dust cap towards the surround costs top
    end. Modelled as a high-shelf cut plus one extra low-pass pole.
    """
    return [
        {"type": "highshelf", "freq": corner_hz, "q": 0.7, "gain_db": shelf_db},
        {"type": "lowpass", "freq": extra_lp_hz, "q": 0.7},
    ]


MODELS = {}


def _register(model):
    MODELS[model["id"]] = model
    return model


# --- Bass cabinets ---------------------------------------------------------

_BASS_810_DRIVER = [
    # Sealed 8x10: a second-order high-pass alignment with a deliberately
    # under-damped Q, which is what gives a sealed bass stack its punch at the
    # box resonance rather than a flat Butterworth roll-off.
    {"type": "highpass", "freq": 55.0, "q": 1.15},
    {"type": "peak", "freq": 80.0, "q": 1.2, "gain_db": 2.5},
    # The box/baffle dip every large multi-driver cabinet has through the low
    # mids, where driver spacing starts to comb against itself.
    {"type": "peak", "freq": 300.0, "q": 1.0, "gain_db": -2.5},
    # 10" cone: the upper-mid growl a 15" does not have.
    {"type": "peak", "freq": 700.0, "q": 1.4, "gain_db": 3.0},
    {"type": "peak", "freq": 1500.0, "q": 2.5, "gain_db": 4.0},
    # First breakup null, then the last mode before the cone stops pistoning.
    {"type": "peak", "freq": 2600.0, "q": 3.5, "gain_db": -4.0},
    {"type": "peak", "freq": 3400.0, "q": 3.0, "gain_db": 2.5},
    # Voice-coil inductance plus cone mass: a steep roll-off, no tweeter.
    {"type": "lowpass", "freq": 4000.0, "q": 0.8},
    {"type": "lowpass", "freq": 5200.0, "q": 0.6},
]

_register({
    "id": "bass-810-cone",
    "display_name": "Modelled 8x10 Cone",
    "file_name": "modelled_8x10_cone.wav",
    "family": "bass",
    "description": "Sealed 8x10 bass stack, generic cardioid dynamic on the dust cap at 2 cm.",
    "sample_rate": 48000,
    "length": 4096,
    "fade_samples": 1024,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": _BASS_810_DRIVER + _dynamic_close_mic(proximity_db=3.0, proximity_hz=110.0),
    }],
    "reflections": [
        # Grille-cloth / baffle-edge return, and the floor bounce a cabinet
        # standing on a stage always has.
        {"path_cm": 26.0, "gain": -0.20, "stages": [{"type": "lowpass", "freq": 3500.0, "q": 0.7}]},
        {"path_cm": 55.0, "gain": 0.12, "stages": [{"type": "lowpass", "freq": 2000.0, "q": 0.7}]},
    ],
})

_register({
    "id": "bass-810-edge",
    "display_name": "Modelled 8x10 Edge",
    "file_name": "modelled_8x10_edge.wav",
    "family": "bass",
    "description": "The same sealed 8x10, microphone moved to the cone edge and angled off-axis.",
    "sample_rate": 48000,
    "length": 4096,
    "fade_samples": 1024,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": _BASS_810_DRIVER
                  + [{"type": "peak", "freq": 220.0, "q": 1.0, "gain_db": 2.0}]
                  + _off_axis(corner_hz=2500.0, shelf_db=-6.0, extra_lp_hz=3200.0)
                  + _dynamic_close_mic(proximity_db=2.0, proximity_hz=110.0, presence_db=1.0),
    }],
    "reflections": [
        {"path_cm": 31.0, "gain": -0.17, "stages": [{"type": "lowpass", "freq": 3000.0, "q": 0.7}]},
        {"path_cm": 55.0, "gain": 0.12, "stages": [{"type": "lowpass", "freq": 2000.0, "q": 0.7}]},
    ],
})

_register({
    "id": "bass-115-vintage",
    "display_name": "Modelled 1x15 Vintage",
    "file_name": "modelled_1x15_vintage.wav",
    "family": "bass",
    "description": "Ported 1x15, dark vintage voicing, generic ribbon microphone at 5 cm.",
    "sample_rate": 48000,
    "length": 4096,
    "fade_samples": 1024,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": [
            # A vented alignment is fourth-order below tuning: two cascaded
            # second-order sections rather than the sealed cabinet's one.
            {"type": "highpass", "freq": 48.0, "q": 0.9},
            {"type": "highpass", "freq": 44.0, "q": 1.4},
            {"type": "peak", "freq": 70.0, "q": 1.4, "gain_db": 3.5},
            {"type": "peak", "freq": 260.0, "q": 1.1, "gain_db": -3.0},
            {"type": "peak", "freq": 550.0, "q": 1.2, "gain_db": 2.0},
            # A 15" cone breaks up lower and dies earlier than a 10".
            {"type": "peak", "freq": 1200.0, "q": 2.0, "gain_db": 2.5},
            {"type": "peak", "freq": 2200.0, "q": 3.0, "gain_db": -5.0},
            {"type": "lowpass", "freq": 2800.0, "q": 0.85},
            {"type": "lowpass", "freq": 3600.0, "q": 0.6},
            # Ribbon: figure-of-eight, so a pronounced proximity rise, and no
            # presence peak at all.
            {"type": "lowshelf", "freq": 100.0, "q": 0.7, "gain_db": 4.0},
            {"type": "highshelf", "freq": 4000.0, "q": 0.7, "gain_db": -4.0},
        ],
    }],
    "reflections": [
        {"path_cm": 30.0, "gain": -0.18, "stages": [{"type": "lowpass", "freq": 2500.0, "q": 0.7}]},
    ],
})

_register({
    "id": "bass-410-horn",
    "display_name": "Modelled 4x10 Horn",
    "file_name": "modelled_4x10_horn.wav",
    "family": "bass",
    "description": "Ported 4x10 with an HF horn on a passive crossover - the modern, extended-top bass voicing.",
    "sample_rate": 48000,
    "length": 4096,
    "fade_samples": 1024,
    "paths": [
        {
            "label": "woofers",
            "gain": 1.0,
            "delay_samples": 0,
            "stages": [
                {"type": "highpass", "freq": 52.0, "q": 0.85},
                {"type": "highpass", "freq": 46.0, "q": 1.3},
                {"type": "peak", "freq": 75.0, "q": 1.3, "gain_db": 3.0},
                {"type": "peak", "freq": 320.0, "q": 1.0, "gain_db": -2.0},
                {"type": "peak", "freq": 900.0, "q": 1.3, "gain_db": 2.5},
                {"type": "peak", "freq": 1800.0, "q": 2.5, "gain_db": 3.0},
                # Crossover low-pass into the horn, 24 dB/octave.
                {"type": "lowpass", "freq": 3000.0, "q": 0.7},
                {"type": "lowpass", "freq": 3200.0, "q": 0.7},
                {"type": "lowshelf", "freq": 120.0, "q": 0.7, "gain_db": 2.0},
            ],
        },
        {
            "label": "horn",
            "gain": 0.50,
            # The horn's acoustic centre sits behind the woofer baffle plane,
            # so its output arrives a fraction of a millisecond late. That
            # offset is the whole reason a real 4x10-plus-horn combs the way it
            # does through the crossover region.
            "delay_samples": 4,
            "stages": [
                {"type": "highpass", "freq": 3600.0, "q": 0.8},
                {"type": "highpass", "freq": 3400.0, "q": 0.7},
                {"type": "peak", "freq": 5500.0, "q": 2.0, "gain_db": 3.0},
                {"type": "peak", "freq": 8000.0, "q": 3.0, "gain_db": -4.0},
                {"type": "lowpass", "freq": 12000.0, "q": 0.7},
            ],
        },
    ],
    "reflections": [
        {"path_cm": 24.0, "gain": -0.16, "stages": [{"type": "lowpass", "freq": 4000.0, "q": 0.7}]},
        {"path_cm": 58.0, "gain": 0.10, "stages": [{"type": "lowpass", "freq": 2000.0, "q": 0.7}]},
    ],
})


# --- Guitar cabinets -------------------------------------------------------

_GUITAR_412_DRIVER = [
    # Sealed 4x12: high-Q second-order alignment, the "thump" at the box
    # resonance that a guitar cabinet lives on.
    {"type": "highpass", "freq": 82.0, "q": 1.2},
    {"type": "peak", "freq": 110.0, "q": 1.6, "gain_db": 3.0},
    # The boxy dip through the lower mids.
    {"type": "peak", "freq": 420.0, "q": 1.1, "gain_db": -4.0},
    {"type": "peak", "freq": 800.0, "q": 1.2, "gain_db": 2.5},
    # Cone-breakup modes: the pair of peaks and the null between them are what
    # makes a 12" guitar speaker sound like one at all.
    {"type": "peak", "freq": 1650.0, "q": 3.2, "gain_db": 6.0},
    {"type": "peak", "freq": 2450.0, "q": 4.5, "gain_db": 5.0},
    {"type": "peak", "freq": 3300.0, "q": 5.0, "gain_db": -7.0},
    {"type": "peak", "freq": 4200.0, "q": 4.0, "gain_db": 3.0},
    # Above the last mode the cone stops radiating: a steep cliff, which is why
    # a cabinet tames fizz that no EQ curve quite can.
    {"type": "lowpass", "freq": 5200.0, "q": 0.8},
    {"type": "lowpass", "freq": 6500.0, "q": 0.6},
]

_register({
    "id": "guitar-412-cone",
    "display_name": "Modelled 4x12 Ceramic Cone",
    "file_name": "modelled_4x12_ceramic_cone.wav",
    "family": "guitar",
    "description": "Sealed 4x12, ceramic-magnet 12\" voicing, dynamic microphone on the dust cap at 2.5 cm.",
    "sample_rate": 48000,
    "length": 2048,
    "fade_samples": 512,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": _GUITAR_412_DRIVER + _dynamic_close_mic(proximity_db=2.0, proximity_hz=150.0,
                                                          presence_db=2.5, presence_hz=5500.0),
    }],
    "reflections": [
        {"path_cm": 22.0, "gain": -0.18, "stages": [{"type": "lowpass", "freq": 4000.0, "q": 0.7}]},
        {"path_cm": 48.0, "gain": 0.10, "stages": [{"type": "lowpass", "freq": 2200.0, "q": 0.7}]},
    ],
})

_register({
    "id": "guitar-412-edge",
    "display_name": "Modelled 4x12 Ceramic Edge",
    "file_name": "modelled_4x12_ceramic_edge.wav",
    "family": "guitar",
    "description": "The same sealed 4x12, microphone at the cone edge and angled - the darker half of a cone/edge blend.",
    "sample_rate": 48000,
    "length": 2048,
    "fade_samples": 512,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": _GUITAR_412_DRIVER
                  + [{"type": "peak", "freq": 250.0, "q": 1.0, "gain_db": 2.0},
                     {"type": "peak", "freq": 2450.0, "q": 4.5, "gain_db": -2.0}]
                  + _off_axis(corner_hz=3000.0, shelf_db=-7.0, extra_lp_hz=4200.0)
                  + _dynamic_close_mic(proximity_db=2.0, proximity_hz=150.0, presence_db=1.0),
    }],
    "reflections": [
        {"path_cm": 27.0, "gain": -0.16, "stages": [{"type": "lowpass", "freq": 3200.0, "q": 0.7}]},
        {"path_cm": 48.0, "gain": 0.10, "stages": [{"type": "lowpass", "freq": 2200.0, "q": 0.7}]},
    ],
})

_register({
    "id": "guitar-412-room",
    "display_name": "Modelled 4x12 Room 1m",
    "file_name": "modelled_4x12_ceramic_room.wav",
    "family": "guitar",
    "description": "Sealed 4x12 at one metre in a small tracking room: no proximity rise, four early reflections and a short diffuse tail.",
    "sample_rate": 48000,
    "length": 8192,
    "fade_samples": 2048,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": _GUITAR_412_DRIVER + [
            # At a metre there is no proximity effect left to speak of, and the
            # extra path costs a little air absorption at the top.
            {"type": "lowshelf", "freq": 120.0, "q": 0.7, "gain_db": -2.0},
            {"type": "highshelf", "freq": 6000.0, "q": 0.7, "gain_db": -2.5},
        ],
    }],
    "reflections": [
        {"path_cm": 65.0, "gain": -0.35, "stages": [{"type": "lowpass", "freq": 3500.0, "q": 0.7}]},
        {"path_cm": 180.0, "gain": -0.25, "stages": [{"type": "lowpass", "freq": 2600.0, "q": 0.7}]},
        {"path_cm": 240.0, "gain": 0.20, "stages": [{"type": "lowpass", "freq": 2200.0, "q": 0.7}]},
        {"path_cm": 330.0, "gain": -0.15, "stages": [{"type": "lowpass", "freq": 1800.0, "q": 0.7}]},
    ],
    "tail": {
        "seed": 0x4E415645,  # "NAVE" - fixed, so the tail is reproducible
        "predelay_cm": 210.0,
        "decay_seconds": 0.11,
        "level_db": -14.0,
        "stages": [
            {"type": "highpass", "freq": 120.0, "q": 0.7},
            {"type": "lowpass", "freq": 4000.0, "q": 0.7},
            {"type": "lowpass", "freq": 5000.0, "q": 0.7},
        ],
    },
})

_register({
    "id": "guitar-212-alnico",
    "display_name": "Modelled 2x12 Alnico Cone",
    "file_name": "modelled_2x12_alnico_cone.wav",
    "family": "guitar",
    "description": "Open-back 2x12, alnico-magnet voicing: earlier breakup, first-order dipole low end, dynamic on the cap.",
    "sample_rate": 48000,
    "length": 2048,
    "fade_samples": 512,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": [
            # Open back radiates as a dipole: the front and rear waves cancel
            # at low frequency, which is a 6 dB/octave slope, not 12.
            {"type": "highpass1", "freq": 130.0},
            {"type": "highpass", "freq": 75.0, "q": 0.7},
            {"type": "peak", "freq": 180.0, "q": 1.0, "gain_db": -3.0},
            {"type": "peak", "freq": 500.0, "q": 1.0, "gain_db": 2.0},
            # An alnico cone breaks up sooner and more musically than ceramic.
            {"type": "peak", "freq": 1900.0, "q": 3.5, "gain_db": 5.5},
            {"type": "peak", "freq": 3100.0, "q": 4.0, "gain_db": 4.0},
            {"type": "peak", "freq": 4000.0, "q": 5.0, "gain_db": -5.0},
            {"type": "peak", "freq": 5000.0, "q": 3.0, "gain_db": 3.0},
            {"type": "lowpass", "freq": 6000.0, "q": 0.8},
            {"type": "lowpass", "freq": 7500.0, "q": 0.6},
        ] + _dynamic_close_mic(proximity_db=1.5, proximity_hz=160.0, presence_db=2.0),
    }],
    "reflections": [
        # The rear wave leaving an open back, bouncing and coming round: the
        # source of the characteristic open-back hollowness.
        {"path_cm": 55.0, "gain": -0.25, "stages": [{"type": "lowpass", "freq": 1800.0, "q": 0.7}]},
        {"path_cm": 90.0, "gain": 0.12, "stages": [{"type": "lowpass", "freq": 1400.0, "q": 0.7}]},
    ],
})

_register({
    "id": "guitar-112-combo",
    "display_name": "Modelled 1x12 Combo Cone",
    "file_name": "modelled_1x12_combo_cone.wav",
    "family": "guitar",
    "description": "Small open-back 1x12 combo: thin low end, a pronounced small-box resonance, dynamic on the cap.",
    "sample_rate": 48000,
    "length": 2048,
    "fade_samples": 512,
    "paths": [{
        "label": "driver",
        "gain": 1.0,
        "delay_samples": 0,
        "stages": [
            {"type": "highpass1", "freq": 160.0},
            {"type": "highpass", "freq": 100.0, "q": 1.1},
            # A small cabinet's own resonance, high enough to be audible as a
            # honk rather than as weight.
            {"type": "peak", "freq": 190.0, "q": 2.5, "gain_db": 4.0},
            {"type": "peak", "freq": 380.0, "q": 1.4, "gain_db": -5.0},
            {"type": "peak", "freq": 1000.0, "q": 1.5, "gain_db": 3.0},
            {"type": "peak", "freq": 2200.0, "q": 3.0, "gain_db": 6.0},
            {"type": "peak", "freq": 3500.0, "q": 4.5, "gain_db": -6.0},
            {"type": "peak", "freq": 4600.0, "q": 3.5, "gain_db": 3.5},
            {"type": "lowpass", "freq": 5800.0, "q": 0.75},
            {"type": "lowpass", "freq": 7000.0, "q": 0.6},
        ] + _dynamic_close_mic(proximity_db=1.5, proximity_hz=170.0, presence_db=2.0),
    }],
    "reflections": [
        {"path_cm": 30.0, "gain": -0.30, "stages": [{"type": "lowpass", "freq": 3000.0, "q": 0.7}]},
        {"path_cm": 62.0, "gain": 0.16, "stages": [{"type": "lowpass", "freq": 1600.0, "q": 0.7}]},
    ],
})


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def select_models(selector):
    if selector in (None, "all"):
        return list(MODELS.values())
    wanted = [token.strip() for token in selector.split(",") if token.strip()]
    chosen = []
    for token in wanted:
        if token in MODELS:
            chosen.append(MODELS[token])
            continue
        family = [model for model in MODELS.values() if model["family"] == token]
        if not family:
            raise SystemExit("unknown model or family: %s" % token)
        chosen.extend(family)
    # De-duplicate while keeping the declaration order stable.
    seen = set()
    ordered = []
    for model in MODELS.values():
        if model["id"] in {m["id"] for m in chosen} and model["id"] not in seen:
            seen.add(model["id"])
            ordered.append(model)
    return ordered


def describe_stage(stage):
    parts = [stage["type"], "%.1f Hz" % stage["freq"]]
    if "q" in stage:
        parts.append("Q %.2f" % stage["q"])
    if "gain_db" in stage:
        parts.append("%+.1f dB" % stage["gain_db"])
    return " ".join(parts)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out-dir", help="directory to write the .wav files into")
    parser.add_argument("--models", default="all",
                        help="comma-separated model ids or families (bass, guitar), or 'all'")
    parser.add_argument("--manifest", help="write a JSON manifest of what was generated")
    parser.add_argument("--list", action="store_true", help="list the models and exit")
    args = parser.parse_args(argv)

    if args.list:
        for model in MODELS.values():
            print("%-22s %-30s %s" % (model["id"], model["display_name"], model["description"]))
        return 0

    if not args.out_dir:
        parser.error("--out-dir is required unless --list is given")

    os.makedirs(args.out_dir, exist_ok=True)

    manifest = {
        "generator": os.path.basename(__file__),
        "generator_sha256": hashlib.sha256(open(__file__, "rb").read()).hexdigest(),
        "speed_of_sound_m_per_s": SPEED_OF_SOUND_M_PER_S,
        "normalisation": "unity peak magnitude response (max |H(f)| = 1.0)",
        "irs": [],
    }

    for model in select_models(args.models):
        impulse = render_model(model)
        normalised, scale, raw_peak = normalise_unity_peak_response(impulse)

        out_path = os.path.join(args.out_dir, model["file_name"])
        clipped, peak_sample = write_wav24(out_path, normalised, model["sample_rate"])
        if clipped:
            raise SystemExit("%s: %d samples clipped on quantisation" % (out_path, clipped))

        digest = hashlib.sha256(open(out_path, "rb").read()).hexdigest()

        stage_lines = []
        for path in model["paths"]:
            for stage in path["stages"]:
                stage_lines.append("%s: %s" % (path["label"], describe_stage(stage)))

        manifest["irs"].append({
            "id": model["id"],
            "display_name": model["display_name"],
            "file": model["file_name"],
            "family": model["family"],
            "description": model["description"],
            "sample_rate": model["sample_rate"],
            "length_samples": model["length"],
            "length_ms": round(1000.0 * model["length"] / model["sample_rate"], 2),
            "channels": 1,
            "bit_depth": 24,
            "normalisation_scale": scale,
            "pre_normalisation_peak_response": raw_peak,
            "peak_sample": round(peak_sample, 6),
            "sections": stage_lines,
            "reflections": [
                {"path_cm": r["path_cm"], "gain": r["gain"],
                 "delay_samples": delay_samples_for_path_cm(r["path_cm"], model["sample_rate"])}
                for r in model.get("reflections", [])
            ],
            "tail": model.get("tail"),
            "sha256": digest,
        })

        print("%-34s %5d samples  %6.2f ms  peak %.4f  sha256 %s"
              % (model["file_name"], model["length"], manifest["irs"][-1]["length_ms"],
                 peak_sample, digest[:16]))

    if args.manifest:
        with open(args.manifest, "w") as handle:
            json.dump(manifest, handle, indent=2, sort_keys=True)
            handle.write("\n")
        print("manifest: %s" % args.manifest)

    return 0


if __name__ == "__main__":
    sys.exit(main())
